version: '3.2'

# Define the services/containers to be run
services:
  db:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      
  web: #name of the service
    build: .
    links:
      - db
    ports:
      - "5100:80"
    environment:
      - DB_SERVER=db
      - DB_PASSWORD=password
	  - DB_ADMIN=5200
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - db
    ports:
      - 5200:80
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=password
      - PMA_ARBITRARY=1